name: "Build"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: godot-build
  PROJECT_PATH: .
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd addons/godot_rust_yaml/rust && cargo build --verbose
    - name: Run tests
      run: cd addons/godot_rust_yaml/rust && cargo test --verbose

  export-windows:
    name: Windows Godot Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd addons/godot_rust_yaml/rust
          apt-get update && apt install -y build-essential && apt-get install -y curl
          apt-get install mingw-w64
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup target add x86_64-pc-windows-gnu
          cargo build --target x86_64-pc-windows-gnu
          cargo build --target x86_64-pc-windows-gnu --release
          cd ../../../
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Godot Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd addons/godot_rust_yaml/rust
          apt-get update && apt install -y build-essential && apt-get install -y curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup target add x86_64-unknown-linux-gnu
          cargo build --target x86_64-unknown-linux-gnu
          cargo build --target x86_64-unknown-linux-gnu --release
          cd ../../../
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux

  export-web:
    name: Web Godot Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd addons/godot_rust_yaml/rust
          apt-get update && apt install -y build-essential && apt-get install -y curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly
          rustup target add wasm32-unknown-emscripten --toolchain nightly
          cargo build --target wasm32-unknown-emscripten
          cargo build --target wasm32-unknown-emscripten --release
          cd ../../../
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
