name: "Build"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: godot-build
  PROJECT_PATH: .
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd addons/godot_rust_yaml/rust && cargo build --verbose
    - name: Run tests
      run: cd addons/godot_rust_yaml/rust && cargo test --verbose

  export-windows:
    name: Windows Godot Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd addons/godot_rust_yaml/rust
          apt-get update && apt install -y build-essential && apt-get install -y curl
          apt-get install -y mingw-w64
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"
          cargo build
          cargo build--release
          cd ../../../
          apt-get install -y tree
          tree
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Godot Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd addons/godot_rust_yaml/rust
          apt-get update && apt install -y build-essential && apt-get install -y curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"
          cargo build
          cargo build --release
          cd ../../../
          apt-get install -y tree
          tree
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
